# Generated by Django 5.0 on 2023-12-13 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoVenta',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('NUMERO_FACTURA', models.CharField(max_length=20, null=True)),
                ('FECHA_EMISION', models.DateField(null=True)),
                ('MONEDA', models.CharField(max_length=60, null=True)),
                ('MONTO', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('TIPO_CLIENTE', models.CharField(max_length=60, null=True)),
                ('NOMBRE_CLIENTE', models.CharField(max_length=150, null=True)),
                ('CONDICION_PAGO', models.CharField(max_length=60, null=True)),
                ('VENDEDOR', models.CharField(max_length=60, null=True)),
                ('CANCELADO', models.CharField(max_length=1, null=True)),
                ('ESTADO', models.CharField(max_length=3, null=True)),
                ('ESTATUS', models.CharField(default='Emitido', max_length=20)),
                ('PERSONAL_ASIGNADO', models.CharField(max_length=80, null=True)),
                ('FECHA_ENTREGA', models.DateField(null=True)),
                ('COMENTARIOS', models.CharField(max_length=400, null=True)),
                ('DATOS_ADJUNTOS', models.BinaryField(null=True)),
            ],
        ),
    ]
