# Generated by Django 5.0 on 2023-12-19 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoventa',
            name='DATOS_ADJUNTOS',
            field=models.BinaryField(editable=True, null=True),
        ),
    ]
