# Generated by Django 5.0 on 2023-12-19 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_documentoventa_datos_adjuntos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoventa',
            name='CANCELADO',
            field=models.CharField(editable=False, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='documentoventa',
            name='CONDICION_PAGO',
            field=models.CharField(editable=False, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='documentoventa',
            name='ESTADO',
            field=models.CharField(editable=False, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='documentoventa',
            name='FECHA_EMISION',
            field=models.DateField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='documentoventa',
            name='MONEDA',
            field=models.CharField(editable=False, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='documentoventa',
            name='MONTO',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='documentoventa',
            name='NOMBRE_CLIENTE',
            field=models.CharField(editable=False, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='documentoventa',
            name='NUMERO_FACTURA',
            field=models.CharField(editable=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='documentoventa',
            name='TIPO_CLIENTE',
            field=models.CharField(editable=False, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='documentoventa',
            name='VENDEDOR',
            field=models.CharField(editable=False, max_length=60, null=True),
        ),
    ]
